version: '3'  # requires Docker Compose 1.13 or later

# This section describes the various containers (services).
services:

  rabbitmq:
    image: 'rabbitmq:3.8.3-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - network

  consumer:
    image: 'php:7.4-cli-alpine'
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    volumes:
      - ./consumer:/consumer
    networks:
      - network

  publisher:
    image: 'php:7.4-cli-alpine'
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    volumes:
      - ./publisher:/publisher
    networks:
      - network

networks:
  network: {}
