version: '3.7'

services:
  php:
    build:
      context: ./Docker/php
    restart: always
    volumes:
      - ./project:/project
    environment:
      PHP_IDE_CONFIG: "serverName=docker"

  nginx:
    depends_on:
      - php
    image: nginx:latest
    ports:
      - "8008:80"
    restart: always
    volumes:
      - ./project:/project
      - ./default.conf:/etc/nginx/conf.d/default.conf
volumes:
  db_data: {}