version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - elasticstacknet
  create_index_pattern:
    build:
      context: ./images/create_index_pattern
    networks:
      - elasticstacknet
  logstash:
    image: logstash:7.0.0
    ports:
      - 5044:5044
    volumes:
      - ./configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elasticstacknet
  kibana:
    image: kibana:7.0.0
    hostname: kibana
    ports:
      - 5601:5601
    networks:
      - elasticstacknet
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.0.0
    container_name: filebeat
    user: root
    volumes:
      - ./configs/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/var/log
    networks:
      - elasticstacknet

volumes:
  elasticdata:
    driver: local

networks:
  elasticstacknet: